import { Project, Job } from "@/types";

export const mockProjects: Project[] = [
  {
    id: 1,
    name: "E-commerce Platform Pro",
    description: "Plataforma completa de e-commerce com Next.js, Stripe e painel administrativo avançado",
    author: "devteam",
    stars: 1234,
    language: "TypeScript",
    tags: ["nextjs", "ecommerce", "stripe"],
    repository: "https://github.com/devteam/ecommerce",
    createdAt: "2026-03-15",
    price: 99.99,
    type: "paid",
    category: "E-commerce",
    rating: 4.8,
    downloads: 5420,
    featured: true,
    demoUrl: "https://demo.ecommerce-pro.com",
    buyUrl: "https://pay.stripe.com/ecommerce-pro",
  },
  {
    id: 2,
    name: "AI Chat Bot",
    description: "Chatbot inteligente usando OpenAI API com suporte a múltiplos idiomas",
    author: "aidev",
    stars: 856,
    language: "Python",
    tags: ["ai", "chatbot", "openai"],
    repository: "https://github.com/aidev/chatbot",
    createdAt: "2026-03-20",
    type: "free",
    category: "Inteligência Artificial",
    rating: 4.5,
    downloads: 12300,
    featured: true,
  },
  {
    id: 3,
    name: "Task Manager Pro",
    description: "Gerenciador de tarefas colaborativo em tempo real com recursos premium",
    author: "productivity",
    stars: 542,
    language: "JavaScript",
    tags: ["react", "firebase", "realtime"],
    repository: "https://github.com/productivity/taskmanager",
    createdAt: "2026-03-25",
    price: 49.99,
    type: "freemium",
    category: "Produtividade",
    rating: 4.6,
    downloads: 8900,
    demoUrl: "https://demo.taskmanager-pro.com",
    buyUrl: "https://pay.stripe.com/taskmanager-pro",
  },
  {
    id: 4,
    name: "Social Network Starter",
    description: "Rede social moderna com feed em tempo real e sistema de notificações",
    author: "socialdev",
    stars: 923,
    language: "TypeScript",
    tags: ["nextjs", "social", "websocket"],
    repository: "https://github.com/socialdev/network",
    createdAt: "2026-04-01",
    type: "free",
    category: "Redes Sociais",
    rating: 4.7,
    downloads: 15600,
    featured: true,
  },
  {
    id: 5,
    name: "Analytics Dashboard",
    description: "Dashboard completo de analytics com gráficos interativos e relatórios",
    author: "datatech",
    stars: 678,
    language: "TypeScript",
    tags: ["react", "charts", "analytics"],
    repository: "https://github.com/datatech/analytics",
    createdAt: "2026-03-28",
    price: 79.99,
    type: "paid",
    category: "Analytics",
    rating: 4.9,
    downloads: 3200,
    demoUrl: "https://demo.analytics-dash.com",
    buyUrl: "https://pay.stripe.com/analytics-dash",
  },
  {
    id: 6,
    name: "CMS Headless",
    description: "Sistema de gerenciamento de conteúdo headless com API GraphQL",
    author: "cmsdev",
    stars: 445,
    language: "TypeScript",
    tags: ["cms", "graphql", "api"],
    repository: "https://github.com/cmsdev/headless",
    createdAt: "2026-03-22",
    type: "free",
    category: "CMS",
    rating: 4.4,
    downloads: 6700,
  },
  {
    id: 7,
    name: "Payment Gateway",
    description: "Gateway de pagamento integrado com múltiplos provedores",
    author: "fintech",
    stars: 892,
    language: "Go",
    tags: ["payment", "api", "fintech"],
    repository: "https://github.com/fintech/payment",
    createdAt: "2026-03-18",
    price: 149.99,
    type: "paid",
    category: "Fintech",
    rating: 4.8,
    downloads: 2100,
    demoUrl: "https://demo.payment-gateway.com",
    buyUrl: "https://pay.stripe.com/payment-gateway",
  },
  {
    id: 8,
    name: "Blog Engine",
    description: "Motor de blog moderno com SEO otimizado e editor markdown",
    author: "blogdev",
    stars: 334,
    language: "JavaScript",
    tags: ["blog", "seo", "markdown"],
    repository: "https://github.com/blogdev/engine",
    createdAt: "2026-03-30",
    type: "free",
    category: "Blog",
    rating: 4.3,
    downloads: 9800,
  },
];

export const mockJobs: Job[] = [
  {
    id: 1,
    title: "Desenvolvedor Full Stack para E-commerce",
    description: "Preciso de um desenvolvedor para criar uma loja virtual completa com integração Stripe e dashboard administrativo. Projeto de média complexidade com prazo definido.",
    skills: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "Tailwind CSS"],
    budget: { type: "range", min: 8000, max: 15000 },
    experienceLevel: "mid",
    duration: "2 a 3 meses",
    location: "Remoto",
    status: "open",
    urgent: true,
    postedAt: "2026-04-03",
    proposalsCount: 12,
    client: { name: "TechStore Brasil", rating: 4.9, jobsPosted: 8 },
  },
  {
    id: 2,
    title: "App Mobile de Delivery (React Native)",
    description: "Aplicativo de delivery similar ao iFood, com rastreamento em tempo real, pagamentos integrados e painel de restaurante.",
    skills: ["React Native", "Node.js", "Firebase", "Maps API", "Redux"],
    budget: { type: "fixed", value: 25000 },
    experienceLevel: "senior",
    duration: "4 a 6 meses",
    location: "Híbrido - São Paulo",
    status: "open",
    urgent: false,
    postedAt: "2026-04-02",
    proposalsCount: 7,
    client: { name: "FoodTech Startup", rating: 4.7, jobsPosted: 3 },
  },
  {
    id: 3,
    title: "Dashboard de Analytics em Tempo Real",
    description: "Criar dashboard interativo com gráficos em tempo real usando WebSockets, ideal para monitoramento de métricas de negócio.",
    skills: ["React", "D3.js", "Socket.io", "Node.js", "Redis"],
    budget: { type: "hourly", min: 80, max: 120 },
    experienceLevel: "expert",
    duration: "1 a 2 meses",
    location: "Remoto",
    status: "open",
    urgent: false,
    postedAt: "2026-04-01",
    proposalsCount: 23,
    client: { name: "DataCorp Analytics", rating: 4.8, jobsPosted: 15 },
  },
  {
    id: 4,
    title: "Integração de IA em Sistema Legado",
    description: "Implementar recursos de IA (NLP) em sistema existente de atendimento ao cliente para automação de respostas.",
    skills: ["Python", "OpenAI API", "FastAPI", "Docker", "AWS"],
    budget: { type: "fixed", value: 12000 },
    experienceLevel: "senior",
    duration: "Menos de 1 mês",
    location: "Remoto",
    status: "open",
    urgent: true,
    postedAt: "2026-04-04",
    proposalsCount: 5,
    client: { name: "SuporteTech", rating: 4.6, jobsPosted: 12 },
  },
  {
    id: 5,
    title: "Landing Page de Alta Conversão",
    description: "Desenvolver landing page otimizada para conversão com animações suaves, formulário multi-step e integração CRM.",
    skills: ["Next.js", "Framer Motion", "Tailwind CSS", "Vercel"],
    budget: { type: "fixed", value: 3500 },
    experienceLevel: "junior",
    duration: "Menos de 1 mês",
    location: "Remoto",
    status: "open",
    urgent: false,
    postedAt: "2026-04-03",
    proposalsCount: 18,
    client: { name: "Marketing Pro", rating: 4.5, jobsPosted: 25 },
  },
  {
    id: 6,
    title: "DevOps Engineer - Configuração CI/CD",
    description: "Configurar pipeline CI/CD completo com GitHub Actions, Docker, Kubernetes e monitoramento para ambiente cloud.",
    skills: ["Docker", "Kubernetes", "GitHub Actions", "Terraform", "AWS"],
    budget: { type: "hourly", min: 100, max: 150 },
    experienceLevel: "expert",
    duration: "1 a 3 meses",
    location: "Remoto",
    status: "open",
    urgent: false,
    postedAt: "2026-03-30",
    proposalsCount: 9,
    client: { name: "CloudFirst", rating: 4.9, jobsPosted: 6 },
  },
];
