"use client";

import { DeveloperCard } from "./DeveloperCard";

const developers = [
  {
    id: 1,
    name: "Ana Silva",
    username: "anasilva",
    avatar: "👩‍💻",
    bio: "Full-stack developer apaixonada por criar soluções inovadoras. Especialista em React e Node.js.",
    rank: 1,
    level: 42,
    xp: 8500,
    maxXp: 10000,
    stats: {
      projects: 28,
      contributions: 1250,
      followers: 342,
      stars: 1840,
    },
    skills: ["React", "Node.js", "TypeScript", "AWS", "Docker"],
    badges: ["🏆", "⭐", "🔥", "💎"],
    isVerified: true,
    isTopContributor: true,
  },
  {
    id: 2,
    name: "Carlos Mendes",
    username: "carlosdev",
    avatar: "👨‍💻",
    bio: "DevOps engineer e cloud architect. Construindo infraestruturas escaláveis e resilientes.",
    rank: 2,
    level: 38,
    xp: 7200,
    maxXp: 9000,
    stats: {
      projects: 22,
      contributions: 980,
      followers: 289,
      stars: 1520,
    },
    skills: ["Kubernetes", "AWS", "Terraform", "Python", "Go"],
    badges: ["🥈", "☁️", "🚀"],
    isVerified: true,
    isTopContributor: true,
  },
  {
    id: 3,
    name: "Beatriz Costa",
    username: "biacosta",
    avatar: "👩‍🎨",
    bio: "UI/UX Designer e Frontend Developer. Criando experiências digitais memoráveis.",
    rank: 3,
    level: 35,
    xp: 6800,
    maxXp: 8500,
    stats: {
      projects: 19,
      contributions: 850,
      followers: 256,
      stars: 1320,
    },
    skills: ["React", "Tailwind", "Figma", "UI/UX", "Animation"],
    badges: ["🥉", "🎨", "✨"],
    isVerified: true,
    isTopContributor: true,
  },
  {
    id: 4,
    name: "Rafael Santos",
    username: "rafaeldev",
    avatar: "🧑‍💻",
    bio: "Backend specialist focado em arquitetura de microsserviços e APIs escaláveis.",
    rank: 4,
    level: 32,
    xp: 5400,
    maxXp: 7500,
    stats: {
      projects: 16,
      contributions: 720,
      followers: 198,
      stars: 980,
    },
    skills: ["Java", "Spring", "PostgreSQL", "Redis", "Kafka"],
    badges: ["⚡", "🔧"],
    isVerified: true,
    isTopContributor: false,
  },
  {
    id: 5,
    name: "Julia Oliveira",
    username: "juliaoliv",
    avatar: "👩‍🔬",
    bio: "Data Scientist e ML Engineer. Transformando dados em insights valiosos.",
    rank: 5,
    level: 30,
    xp: 4900,
    maxXp: 7000,
    stats: {
      projects: 14,
      contributions: 650,
      followers: 175,
      stars: 840,
    },
    skills: ["Python", "TensorFlow", "Pandas", "SQL", "Jupyter"],
    badges: ["🧠", "📊"],
    isVerified: true,
    isTopContributor: false,
  },
  {
    id: 6,
    name: "Pedro Alves",
    username: "pedroalves",
    avatar: "👨‍🚀",
    bio: "Mobile developer criando apps nativos incríveis para iOS e Android.",
    rank: 6,
    level: 28,
    xp: 4200,
    maxXp: 6500,
    stats: {
      projects: 12,
      contributions: 580,
      followers: 142,
      stars: 720,
    },
    skills: ["React Native", "Swift", "Kotlin", "Flutter", "Firebase"],
    badges: ["📱", "🎯"],
    isVerified: false,
    isTopContributor: false,
  },
  {
    id: 7,
    name: "Mariana Lima",
    username: "marialima",
    avatar: "👩‍🏫",
    bio: "Tech lead e mentora. Ajudando desenvolvedores a crescerem em suas carreiras.",
    rank: 7,
    level: 26,
    xp: 3800,
    maxXp: 6000,
    stats: {
      projects: 10,
      contributions: 520,
      followers: 128,
      stars: 650,
    },
    skills: ["Leadership", "React", "Node.js", "Mentoring", "Agile"],
    badges: ["👨‍🏫", "💡"],
    isVerified: true,
    isTopContributor: false,
  },
  {
    id: 8,
    name: "Lucas Ferreira",
    username: "lucasferr",
    avatar: "🧑‍🎓",
    bio: "Desenvolvedor júnior em constante aprendizado. Focado em web development.",
    rank: 8,
    level: 18,
    xp: 2100,
    maxXp: 4000,
    stats: {
      projects: 6,
      contributions: 280,
      followers: 68,
      stars: 320,
    },
    skills: ["JavaScript", "React", "HTML", "CSS", "Git"],
    badges: ["🌱"],
    isVerified: false,
    isTopContributor: false,
  },
];

export function DeveloperGrid() {
  return (
    <div className="mt-8">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {developers.map((developer) => (
          <DeveloperCard key={developer.id} developer={developer} showRank />
        ))}
      </div>
    </div>
  );
}
